/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamingecommerceapp;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author mabookair
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
        
     
        //centering the screen
        setLocationRelativeTo(null);
        
        AppData.frHome=this;
        
        //first product image (red dead)
        String picSrc = "/pkgAppImages/red dead.jpg";
        Image pic = Toolkit.getDefaultToolkit().getImage(getClass().getResource(picSrc));
        pic = pic.getScaledInstance(lblRedDead.getWidth(), lblRedDead.getHeight(), 2);
        lblRedDead.setIcon(new ImageIcon(pic));
        
        //second product image (cod mw)
        String pic1Src = "/pkgAppImages/cod mw.jpg";
        Image pic1 = Toolkit.getDefaultToolkit().getImage(getClass().getResource(pic1Src));
        pic1 = pic1.getScaledInstance(lblCODMW.getWidth(), lblCODMW.getHeight(), 2);
        lblCODMW.setIcon(new ImageIcon(pic1));
        
        //third product image (GTA 5)
        String pic2Src = "/pkgAppImages/GTA 5.jpg";
        Image pic2 = Toolkit.getDefaultToolkit().getImage(getClass().getResource(pic2Src));
        pic2 = pic2.getScaledInstance(lblGTA.getWidth(), lblGTA.getHeight(), 2);
        lblGTA.setIcon(new ImageIcon(pic2));
        
        //fourth product image (Fallout76)
        String pic3Src = "/pkgAppImages/fallout76.jpg";
        Image pic3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource(pic3Src));
        pic3 = pic3.getScaledInstance(lblFallout76.getWidth(), lblFallout76.getHeight(), 2);
        lblFallout76.setIcon(new ImageIcon(pic3));
        
        //fifth product image (star wars battlefront 2)
        String pic4Src = "/pkgAppImages/SWB2.jpg";
        Image pic4 = Toolkit.getDefaultToolkit().getImage(getClass().getResource(pic4Src));
        pic4 = pic4.getScaledInstance(lblSWB2.getWidth(), lblSWB2.getHeight(), 2);
        lblSWB2.setIcon(new ImageIcon(pic4));
        
         //logo image 
        String pic5Src = "/pkgAppImages/gaming controller.png";
        Image pic5 = Toolkit.getDefaultToolkit().getImage(getClass().getResource(pic5Src));
        pic5 = pic5.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), 2);
        lblLogo.setIcon(new ImageIcon(pic5));
        lblLogo.setText(" ");
        
       
        
    }  
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateNewAccount = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEnterUsername = new javax.swing.JTextField();
        lblWelcome = new javax.swing.JLabel();
        lblCurrentUsername = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        pwdUserPassword = new javax.swing.JPasswordField();
        lblUserAmount = new javax.swing.JLabel();
        lblAmountOfUsers = new javax.swing.JLabel();
        btnUserDetails = new javax.swing.JButton();
        lblAdminOnly = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        lblLoginAttempt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlProducts = new javax.swing.JPanel();
        lblRedDead = new javax.swing.JLabel();
        lblRDDescription = new javax.swing.JLabel();
        btnAddRD = new javax.swing.JButton();
        lbl£ = new javax.swing.JLabel();
        lblDivider1 = new javax.swing.JLabel();
        lblCODMW = new javax.swing.JLabel();
        lblCODDescription = new javax.swing.JLabel();
        lblCODPrice = new javax.swing.JLabel();
        lbl£1 = new javax.swing.JLabel();
        btnAddCOD = new javax.swing.JButton();
        lblDivider2 = new javax.swing.JLabel();
        lblGTA = new javax.swing.JLabel();
        lblGTADescription = new javax.swing.JLabel();
        btnAddGTA5 = new javax.swing.JButton();
        lblGTAPrice = new javax.swing.JLabel();
        lbl£2 = new javax.swing.JLabel();
        lblDivider3 = new javax.swing.JLabel();
        lblFallout76 = new javax.swing.JLabel();
        lblFO76Description = new javax.swing.JLabel();
        btnAddFO76 = new javax.swing.JButton();
        lblFO76Price = new javax.swing.JLabel();
        lbl£3 = new javax.swing.JLabel();
        lblDivider4 = new javax.swing.JLabel();
        lblSWB2 = new javax.swing.JLabel();
        lblSWB2Description = new javax.swing.JLabel();
        btnAddSWB2 = new javax.swing.JButton();
        lbl£4 = new javax.swing.JLabel();
        lblSWB2Price = new javax.swing.JLabel();
        lblCODMWTitle = new javax.swing.JLabel();
        lblGTA5Title = new javax.swing.JLabel();
        lblFO76Title = new javax.swing.JLabel();
        lblSWB2Title = new javax.swing.JLabel();
        txtRDR2Title = new javax.swing.JTextField();
        txtRDR2Price = new javax.swing.JTextField();
        btnBasket = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblValidate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gaming.com Ecommerce");
        setBackground(new java.awt.Color(204, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnCreateNewAccount.setBackground(new java.awt.Color(229, 228, 226));
        btnCreateNewAccount.setText("Create New Account");
        btnCreateNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewAccountActionPerformed(evt);
            }
        });

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("DIN Condensed", 3, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(153, 0, 0));
        lblUsername.setText("Username: ");
        lblUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("DIN Condensed", 3, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 0, 0));
        lblPassword.setText("Password:");
        lblPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtEnterUsername.setBackground(new java.awt.Color(229, 228, 226));
        txtEnterUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterUsernameActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(153, 0, 0));
        lblWelcome.setText("Welcome,  ");

        lblCurrentUsername.setFont(new java.awt.Font("Euphemia UCAS", 0, 18)); // NOI18N
        lblCurrentUsername.setForeground(new java.awt.Color(153, 0, 0));
        lblCurrentUsername.setText("Anonymous User  ");

        btnLogOut.setBackground(new java.awt.Color(229, 228, 226));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        pwdUserPassword.setBackground(new java.awt.Color(229, 228, 226));

        lblUserAmount.setText("Users:");

        lblAmountOfUsers.setText("0");

        btnUserDetails.setBackground(new java.awt.Color(229, 228, 226));
        btnUserDetails.setText("Users Details");
        btnUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDetailsActionPerformed(evt);
            }
        });

        lblAdminOnly.setText("Admin Only");

        btnLogin1.setBackground(new java.awt.Color(229, 228, 226));
        btnLogin1.setText("Log In");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        lblLoginAttempt.setForeground(new java.awt.Color(0, 153, 51));
        lblLoginAttempt.setText("Please login.");

        pnlProducts.setBackground(new java.awt.Color(255, 255, 255));
        pnlProducts.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Products", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N

        lblRedDead.setText("lblRedDead");

        lblRDDescription.setText("<html> Red Dead Redemption 2 is a 2018 action-adventure game developed and published by Rockstar Games. The game is the third entry in the Red Dead series and is a prequel to the 2010 game Red Dead Redemption. The story is set in 1899 in a fictionalized representation of the Western, Midwestern and Southern United States and follows outlaw Arthur Morgan, a member of the Van der Linde gang.");

        btnAddRD.setText("Add to Basket");
        btnAddRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRDActionPerformed(evt);
            }
        });

        lbl£.setText("£");

        lblDivider1.setText("--------------------------------------------------------------------------------------------");

        lblCODMW.setText("lblCODMW");

        lblCODDescription.setText("<html> Call of Duty: Modern Warfare is a 2019 first-person shooter video game developed by Infinity Ward and published by Activision. Serving as the sixteenth overall installment in the Call of Duty series, as well as a reboot of the Modern Warfare sub-series, it was released on October 25, 2019, for Microsoft Windows, PlayStation 4, and Xbox One.");

        lblCODPrice.setText("50");

        lbl£1.setText("£");

        btnAddCOD.setText("Add to Basket");
        btnAddCOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCODActionPerformed(evt);
            }
        });

        lblDivider2.setText("--------------------------------------------------------------------------------------------");

        lblGTA.setText("lblGTA");

        lblGTADescription.setText("<html>Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the first main entry in the Grand Theft Auto series since 2008's Grand Theft Auto IV. Set within the fictional state of San Andreas, based on Southern California, the single-player story follows three criminals and their efforts to commit heists while under pressure from a government agency and powerful crime figures.");

        btnAddGTA5.setText("Add to Basket");
        btnAddGTA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGTA5ActionPerformed(evt);
            }
        });

        lblGTAPrice.setText("25");

        lbl£2.setText("£");

        lblDivider3.setText("--------------------------------------------------------------------------------------------");

        lblFallout76.setText("lblFallout76");

        lblFO76Description.setText("<html>Fallout 76 is an online action role-playing game developed by Bethesda Game Studios and published by Bethesda Softworks. Released for Microsoft Windows, PlayStation 4, and Xbox One on November 14, 2018, it is an installment in the Fallout series and a prequel to previous entries. Fallout 76 is Bethesda Game Studios's first multiplayer game; players explore the open world, which has been torn apart by nuclear war, with others.");

        btnAddFO76.setText("Add to Basket");
        btnAddFO76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFO76ActionPerformed(evt);
            }
        });

        lblFO76Price.setText("30");

        lbl£3.setText("£");

        lblDivider4.setText("--------------------------------------------------------------------------------------------");

        lblSWB2.setText("lblSWB2");

        lblSWB2Description.setText("<html> Star Wars Battlefront II is an action shooter video game based on the Star Wars film franchise. It is the fourth major installment of the Star Wars: Battlefront series and seventh overall, and a sequel to the 2015 reboot of the series. It was developed by EA DICE, in collaboration with Criterion Games and Motive Studios, and published by Electronic Arts. The game was released worldwide on November 17, 2017 for PlayStation 4, Xbox One, and Microsoft Windows.");

        btnAddSWB2.setText("Add to Basket");
        btnAddSWB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSWB2ActionPerformed(evt);
            }
        });

        lbl£4.setText("£");

        lblSWB2Price.setText("30");

        lblCODMWTitle.setForeground(new java.awt.Color(153, 0, 0));
        lblCODMWTitle.setText("Call Of Duty: Modern Warfare");

        lblGTA5Title.setForeground(new java.awt.Color(153, 0, 0));
        lblGTA5Title.setText("Grand Theft Auto 5");

        lblFO76Title.setForeground(new java.awt.Color(153, 0, 0));
        lblFO76Title.setText("Fallout 76");

        lblSWB2Title.setForeground(new java.awt.Color(153, 0, 0));
        lblSWB2Title.setText("Star Wars Battlefront 2");

        txtRDR2Title.setEditable(false);
        txtRDR2Title.setBackground(new java.awt.Color(255, 255, 255));
        txtRDR2Title.setForeground(new java.awt.Color(153, 0, 0));
        txtRDR2Title.setText("Red Dead Redemption 2");

        txtRDR2Price.setText("30");
        txtRDR2Price.setBorder(null);

        javax.swing.GroupLayout pnlProductsLayout = new javax.swing.GroupLayout(pnlProducts);
        pnlProducts.setLayout(pnlProductsLayout);
        pnlProductsLayout.setHorizontalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDivider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDivider2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFallout76, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFO76Description, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(lblFO76Title, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddFO76))
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(lbl£3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFO76Price)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblDivider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDivider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblCODMW, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCODDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addComponent(lbl£1)
                                        .addGap(1, 1, 1)
                                        .addComponent(lblCODPrice))
                                    .addComponent(btnAddCOD)))
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblGTA, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblGTADescription, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAddGTA5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(lbl£2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblGTAPrice))))
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(lblGTA5Title, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSWB2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSWB2Description, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(btnAddSWB2))
                                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(lbl£4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblSWB2Price))))
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(lblSWB2Title, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblRedDead, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProductsLayout.createSequentialGroup()
                                        .addComponent(lblRDDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAddRD)
                                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                                .addComponent(lbl£)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtRDR2Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtRDR2Title, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(lblCODMWTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProductsLayout.setVerticalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductsLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtRDR2Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRedDead, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRDDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl£)
                            .addComponent(txtRDR2Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddRD)))
                .addGap(18, 18, 18)
                .addComponent(lblDivider1)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblCODMWTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCODMW, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCODDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCODPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl£1))
                        .addGap(27, 27, 27)
                        .addComponent(btnAddCOD)))
                .addGap(18, 18, 18)
                .addComponent(lblDivider2)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblGTA5Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGTADescription, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblGTA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGTAPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl£2))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddGTA5)))
                .addGap(18, 18, 18)
                .addComponent(lblDivider3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductsLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFO76Price, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl£3)))
                            .addComponent(lblFO76Title))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFO76Description, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddFO76)))
                    .addComponent(lblFallout76, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDivider4)
                .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSWB2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblSWB2Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSWB2Description, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlProductsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSWB2Price, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl£4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddSWB2)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(pnlProducts);

        btnBasket.setBackground(new java.awt.Color(229, 228, 226));
        btnBasket.setText("Basket");
        btnBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasketActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(229, 228, 226));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("DIN Condensed", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Gaming.com ");

        lblLogo.setText("lblLogo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblValidate.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pwdUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblValidate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)
                                .addComponent(btnUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblUserAmount)
                                .addGap(18, 18, 18)
                                .addComponent(lblAmountOfUsers))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(lblAdminOnly))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblWelcome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblLoginAttempt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserAmount)
                            .addComponent(lblAmountOfUsers)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCreateNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUserDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdminOnly)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblLoginAttempt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(pwdUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWelcome)
                            .addComponent(lblCurrentUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogin1)
                            .addComponent(btnLogOut)
                            .addComponent(btnBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValidate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @author Jack McNslly
     * @version 1.0
     * This code will allow create a new account object while
     * hiding the home/main screen and showing the the create an
     * account screen just by clicking the create new account button. 
     * @param evt 
     */
    private void btnCreateNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewAccountActionPerformed
        this.setVisible(false);
        AppData.frNewUser = new MakeNewAccount();
        AppData.frNewUser.setVisible(true);
    }//GEN-LAST:event_btnCreateNewAccountActionPerformed
    
    /**
     * This button is less complex and simply creates a new 
     * instance of the basket method and sets the home screen to be
     * invisible and the basket screen to be visible.
     * @param evt 
     */
    private void btnBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasketActionPerformed
         this.setVisible(false);
         new Basket().setVisible(true);
    }//GEN-LAST:event_btnBasketActionPerformed

    private void txtEnterUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterUsernameActionPerformed
      
    }//GEN-LAST:event_txtEnterUsernameActionPerformed

    /**
     * @author Jack McNally 
     * @version 1.0
     * The code for this button will allow the user to log out if they 
     * have logged in by clearing the login fields, setting
     * the welcome messages username greeting back to anonymous
     * @param evt 
     */
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        txtEnterUsername.setText("");
        pwdUserPassword.setText("");
        lblCurrentUsername.setText("Anonymous User");
        lblWelcome.setText("Welcome,"); 
    }//GEN-LAST:event_btnLogOutActionPerformed
  
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // setting the label count to increase as new user accounts are made
        lblAmountOfUsers.setText(String.valueOf(AppData.count));
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * This code will be the source code behind users details button and will only
     * grant access to the user details screen if a user with an authorised admin
     * username is logged in. The button will then grant access to the user if they 
     * are an admin but if not they a access denied message will display in the 
     * label below the button.     
     * @author Jack McNally
     * @version 1.0
     * @param evt 
     */
    private void btnUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDetailsActionPerformed
        if(lblCurrentUsername.getText().equals("Admin") || 
           lblCurrentUsername.getText().equals("admin") || 
           lblCurrentUsername.getText().equals("ADMIN"))
        {   
            lblAdminOnly.setText("Access granted");
            this.setVisible(false);
            new UserDetails().setVisible(true);
        }
        else
        {
            lblAdminOnly.setText("Unauthorised user");
        }
                    
    }//GEN-LAST:event_btnUserDetailsActionPerformed

    /**
     * @author Jack McNally
     * The code behind this button will allow the user to login to 
     * an account they created and have stored in the accounts array
     * within the AppData class. It will check if the username and password to
     * see if it is present in any of the user accounts objects and if they are 
     * then the user will be logged in and display the users username in the 
     * welcome label. It will throw an error if the button is clicked with blank
     * login fields or if the username and/or password is not valid.
     * @return user is logged in 
     * @param evt 
     * 
     */
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        
        String username = txtEnterUsername.getText();
        String password = pwdUserPassword.getText();
        
       for(int index=0; index < AppData.count; index ++)
        {
            if(username.equals(AppData.accounts[index].getUsername())
              &&(password.equals(AppData.accounts[index].getPassword()))) 
            {
                lblCurrentUsername.setText(username);
                lblWelcome.setText("Welcome back,"); 
                lblLoginAttempt.setText("Login Successful");
                txtEnterUsername.setText("");
                pwdUserPassword.setText("");
                lblValidate.setText("");
                AppData.currentUser.equals(username);
                return;
            }
            else 
            {
                lblValidate.setText("Invalid Login");
                
            }
 
            
        }// end of for
       if(username.isEmpty() && password.isEmpty())
       {
           lblValidate.setText("Invalid Login");
       }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnAddRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRDActionPerformed
        //AppData.frBasket.txtaBasket.setText(AppData.products[0].getItemName() + " "+ AppData.products[0].getItemPrice());
        String product1 = txtRDR2Title.getText();
        double price1 = Integer.parseInt(txtRDR2Price.getText());
       
       
        BasketItems product01 = new BasketItems(product1,  price1 );
        AppData.products[AppData.productcount] = product01;
        AppData.productcount ++;
        
        AppData.frBasket.lblCurrentBasket.setText("Items currently in basket:");
        AppData.total += price1;
        
    }//GEN-LAST:event_btnAddRDActionPerformed

    /**
     * The code I've created below is the first of the code behind the add to basket 
     * button and will be the same structure for every add to basket button on each 
     * of the products listed on the application. It will add the name of the product
     * and the price to a new basket item object and store it in the basket array
     * which will be used to display the items the user has added to their basket 
     * in the list box on the basket screen. 
     * @param evt 
     * 
     */
    private void btnAddCODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCODActionPerformed
         
        String product2 = lblCODMWTitle.getText();
        double price2 = Integer.parseInt(lblCODPrice.getText());
        
       
        BasketItems product02 = new BasketItems(product2,  price2 );
        AppData.products[AppData.productcount] = product02;
        AppData.productcount ++;
        
        AppData.frBasket.lblCurrentBasket.setText("Items currently in basket:");
        AppData.total += price2;
    }//GEN-LAST:event_btnAddCODActionPerformed

    private void btnAddGTA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGTA5ActionPerformed
        String product3 = lblGTA5Title.getText();
        double price3 = Integer.parseInt(lblGTAPrice.getText());
        
       
        BasketItems product03 = new BasketItems(product3,  price3 );
        AppData.products[AppData.productcount] = product03;
        AppData.productcount ++;
        
        AppData.frBasket.lblCurrentBasket.setText("Items currently in basket:");
        AppData.total += price3;
    }//GEN-LAST:event_btnAddGTA5ActionPerformed

    private void btnAddFO76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFO76ActionPerformed
        String product4 = lblFO76Title.getText();
        double price4 = Integer.parseInt(lblFO76Price.getText());
       
       
        BasketItems product04 = new BasketItems(product4,  price4 );
        AppData.products[AppData.productcount] = product04;
        AppData.productcount ++;
        
        AppData.frBasket.lblCurrentBasket.setText("Items currently in basket:");
         AppData.total += price4;
    }//GEN-LAST:event_btnAddFO76ActionPerformed

    private void btnAddSWB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSWB2ActionPerformed
        String product5 = lblSWB2Title.getText();
        double price5 = Integer.parseInt(lblSWB2Price.getText());
       
       
        BasketItems product05 = new BasketItems(product5,  price5 );
        AppData.products[AppData.productcount] = product05;
        AppData.productcount ++;
        
        AppData.frBasket.lblCurrentBasket.setText("Items currently in basket:");
         AppData.total += price5;
    }//GEN-LAST:event_btnAddSWB2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCOD;
    private javax.swing.JButton btnAddFO76;
    private javax.swing.JButton btnAddGTA5;
    private javax.swing.JButton btnAddRD;
    private javax.swing.JButton btnAddSWB2;
    private javax.swing.JButton btnBasket;
    private javax.swing.JButton btnCreateNewAccount;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnUserDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdminOnly;
    private javax.swing.JLabel lblAmountOfUsers;
    private javax.swing.JLabel lblCODDescription;
    private javax.swing.JLabel lblCODMW;
    private javax.swing.JLabel lblCODMWTitle;
    private javax.swing.JLabel lblCODPrice;
    public static javax.swing.JLabel lblCurrentUsername;
    private javax.swing.JLabel lblDivider1;
    private javax.swing.JLabel lblDivider2;
    private javax.swing.JLabel lblDivider3;
    private javax.swing.JLabel lblDivider4;
    private javax.swing.JLabel lblFO76Description;
    private javax.swing.JLabel lblFO76Price;
    private javax.swing.JLabel lblFO76Title;
    private javax.swing.JLabel lblFallout76;
    private javax.swing.JLabel lblGTA;
    private javax.swing.JLabel lblGTA5Title;
    private javax.swing.JLabel lblGTADescription;
    private javax.swing.JLabel lblGTAPrice;
    private javax.swing.JLabel lblLoginAttempt;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRDDescription;
    private javax.swing.JLabel lblRedDead;
    private javax.swing.JLabel lblSWB2;
    private javax.swing.JLabel lblSWB2Description;
    private javax.swing.JLabel lblSWB2Price;
    private javax.swing.JLabel lblSWB2Title;
    private javax.swing.JLabel lblUserAmount;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblValidate;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lbl£;
    private javax.swing.JLabel lbl£1;
    private javax.swing.JLabel lbl£2;
    private javax.swing.JLabel lbl£3;
    private javax.swing.JLabel lbl£4;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JPasswordField pwdUserPassword;
    private javax.swing.JTextField txtEnterUsername;
    public static javax.swing.JTextField txtRDR2Price;
    public static javax.swing.JTextField txtRDR2Title;
    // End of variables declaration//GEN-END:variables


  

}
