/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamingecommerceapp;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author mabookair
 */
public class MakeNewAccount extends javax.swing.JFrame {

          public static UserAccounts acc1;
          
        
    /**
     * Creates new form MakeNewAccount
     */
    public MakeNewAccount() {
        initComponents();
        
          //centring the screen 
        setLocationRelativeTo(null); 
        
        AppData.frNewUser=this;
        
         //logo image 
        String picSrc = "/pkgAppImages/gaming controller.png";
        Image pic = Toolkit.getDefaultToolkit().getImage(getClass().getResource(picSrc));
        pic = pic.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), 2);
        lblLogo.setIcon(new ImageIcon(pic));
        
        //setting labels to be used in validation to blank
        lblVALFN.setText(" ");
        lblVALSN.setText(" ");
        
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnCloseCreateAccount = new javax.swing.JButton();
        txtNewAddress = new javax.swing.JTextField();
        lblCreationMessage = new javax.swing.JLabel();
        txtNewPostcode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNewSurname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblSurnameText = new javax.swing.JLabel();
        lblBusiness = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNewUsername = new javax.swing.JTextField();
        btnCreateAccount = new javax.swing.JButton();
        txtNewFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        lblVALFN = new javax.swing.JLabel();
        lblVALSN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 51));
        lblTitle.setText("                         Create Account");

        btnCloseCreateAccount.setText("Close");
        btnCloseCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseCreateAccountActionPerformed(evt);
            }
        });

        lblCreationMessage.setFont(new java.awt.Font("Gujarati Sangam MN", 1, 12)); // NOI18N
        lblCreationMessage.setForeground(new java.awt.Color(153, 0, 0));
        lblCreationMessage.setText("Please fill out details below");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Username: ");

        txtNewSurname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewSurnameKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("First Name:");

        lblSurnameText.setBackground(new java.awt.Color(255, 255, 255));
        lblSurnameText.setForeground(new java.awt.Color(204, 0, 51));
        lblSurnameText.setText("Surname: ");

        lblBusiness.setFont(new java.awt.Font("DIN Condensed", 3, 14)); // NOI18N
        lblBusiness.setText("Gaming.com ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Address: ");

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        txtNewFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewFirstNameKeyPressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Postcode:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Password:");

        lblLogo.setText("jLabel3");

        lblVALFN.setText("jLabel6");

        lblVALSN.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnCreateAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBusiness)
                        .addGap(67, 67, 67)
                        .addComponent(lblCreationMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSurnameText)
                                .addGap(26, 26, 26)
                                .addComponent(txtNewSurname))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(txtNewAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(txtNewPostcode))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVALFN)
                    .addComponent(lblVALSN))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreationMessage))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseCreateAccount)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVALFN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSurnameText)
                            .addComponent(txtNewSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVALSN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNewPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnCreateAccount))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseCreateAccountActionPerformed
        this.setVisible(false);
        AppData.frHome.setVisible(true);
    }//GEN-LAST:event_btnCloseCreateAccountActionPerformed
    
   
     
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
       
        if(AppData.count == AppData.accounts.length)
        {
            lblCreationMessage.setText("Max Accounts Made");
            return;
        } 
            if((txtNewUsername.getText()).equals("")
            || (txtNewFirstName.getText()).equals("")
            || (txtNewSurname.getText()).equals("")
            || (txtNewAddress.getText()).equals("")
            || (txtNewPostcode.getText()).equals("")
            || (txtPassword.getText()).equals(""))
            

                {
                    lblCreationMessage.setText("Account creation failed");
                    return;
                }
            
            
            
            
        try {
        String username = txtNewUsername.getText();
        String firstname = txtNewFirstName.getText();
        String surname = txtNewSurname.getText();
        String address = txtNewAddress.getText();
        String postcode = txtNewPostcode.getText();
        String password = txtPassword.getText();
        
        UserAccounts tempAcc = new UserAccounts(username, firstname, surname, address, postcode, password);
        AppData.accounts[AppData.count] = tempAcc;
        
        AppData.count++;
        
         lblCreationMessage.setText("Account created.");
         txtNewUsername.setText("");
         txtNewFirstName.setText("");
         txtNewSurname.setText("");
         txtNewAddress.setText("");   
         txtNewPostcode.setText("");
         txtPassword.setText("");
        }
        catch (Exception e){
            lblCreationMessage.setText("Max accounts made");
        }
        
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void txtNewFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewFirstNameKeyPressed
        //code to only allow letters, space and backspace keys
        // this will validate the field and only allow letters for entering a 
        //first name
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) 
          || Character.isISOControl(c))
        //the iso control is for the edit oepration (baskspace/delete key allowed)
        //if the character is a letter, the space/iso controls allow to edit    
        {
            txtNewFirstName.setEditable(true);
        }else
        {
            txtNewFirstName.setEditable(false);
            lblVALFN.setText("Letters only.");
        }
        
    }//GEN-LAST:event_txtNewFirstNameKeyPressed

    private void txtNewSurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewSurnameKeyPressed
      //code to only allow letters, space and backspace keys
        // this will validate the field and only allow letters for entering a 
        //first name
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c) || Character.isWhitespace(c) 
          || Character.isISOControl(c))
        //the iso control is for the edit operation (baskspace/delete key allowed)
        //if the character is a letter, the space/iso controls allow to edit    
        {
            txtNewSurname.setEditable(true);
        }else
        {
            txtNewSurname.setEditable(false);
            lblVALSN.setText("Letters only.");
        }
    }//GEN-LAST:event_txtNewSurnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseCreateAccount;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBusiness;
    private javax.swing.JLabel lblCreationMessage;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSurnameText;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVALFN;
    private javax.swing.JLabel lblVALSN;
    private javax.swing.JTextField txtNewAddress;
    private javax.swing.JTextField txtNewFirstName;
    private javax.swing.JTextField txtNewPostcode;
    private javax.swing.JTextField txtNewSurname;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
